### ISSUE TITLE
Suggested changes to options

### ISSUE THREAD

**Issue by dendritic** [cortex-lab/Suite2P#1]
1. Naming in the option structure is a bit chaotic. How painful would it be to rename some of the options to to make them more intuitive and consistent? e.g. ```nimgbegend```, ```Nk Nk0``` and ```niterclustering``` and ```RootStorage```. Ideally all options would be reasonably understandable from their name and would have consistent casing, that is idiomatic MATLAB. MathWorks usually use ```camelCasing``` for structure fields with a lower case initial letter. We could also use substructures to create namespaces to help further tidy it up. e.g. ```ops.reg.targetFrame```.
2. Many of the functions would be more lightweight if they didn't require the options structure to be passed in and used some sensible defaults. I suggest we make it an optional last argument of the functions. A simple way to reduce the code overhead for handling defaults inside the functions is to use a pattern like ```theOption = getOr(ops, 'theOption', 'some default value')```.

**Comment by dendritic** [comment]
My latest commit has an example implementation of getOr which may also help with renaming options without breaking stuff. It allows you to specify multiple field names and check them all, returning the first that matches or the default: ```theOption = getOr(ops, {'theOption' 'oldname'}, 57)```

**Comment by marius10p** [comment]
I defaulted a lot of the options in the run_pipeline main script (using your getOr function). Would have been too painful to change variable names everywhere, but they are fully documented in the master_file_example.
