### ISSUE TITLE
BiDiPhase error

### ISSUE THREAD

**Issue by jbiane** [cortex-lab/Suite2P#104]
Just starting using Suite2p – looks like you have a great tool here!
I’m running into an issue with/following registration. With some imaging sessions, after registration completes, I get the following error:

Undefined function or variable 'BiDiPhase'.
Error in getRangeNoOutliers (line 59)
        elseif BiDiPhase<0
Error in reg2P (line 341)
    ops1 = getRangeNoOutliers(ops, ops1);
Error in run_pipeline (line 38)
    ops1 = reg2P(ops0);  % do registration

I’ve no idea why I get this error on some vids but not others. It occurs whether I’m registering tiff stacks or a multi-image tiff. It seems that every time I get this error, the bi-directional scanning offset = 0 pixels (when the value = 1, I don’t get the error).
Any insight? It seems to motion correct the videos just fine, but just throws that error after registration and it can’t move on to ROI. I thought maybe setting ops0.dobidi = 0 in the master file could help, but no. I’m using Matlab versions R2016b and 2017a.

**Comment by carsen-stringer** [comment]
Can you pull the latest version of the code, it should be fixed there. I'm really sorry, if the bidiphase is 1 it won't get to this line (it will enter the first if statement which is correct).

**Comment by jbiane** [comment]
All good now. Thanks for the quick fix!
