### ISSUE TITLE
master_file tag format issues 

### ISSUE THREAD

**Issue by carlyrosewilling** [cortex-lab/Suite2P#106]
When I try to run the master_file using a db with only 9 tiffs with 5000 frames each, MATLAB get's stuck in a loop with continual error messages reading "Warning: Did not recognize tag format ####", where the #'s correspond to various different four digit and five digit numbers. The application then becomes unresponsive and requires a force quit. I was wondering how to fix this so that I may run the main pipeline correctly? Also, what is the easiest way to just run registration without going on to the other steps in the pipeline. Thanks!

**Comment by carsen-stringer** [comment]
We try to read the tiff header in "build_ops3.m" to get more information about the recording. What information is there will depend on your acquisition software. I've added an option to not read the headers. Set
`ops0.readTiffHeader = 0;`
in your master_file.

To run just registration, you can set
`ops0.getROIs = 0;`

If you want to keep the binary files after processing (the registered frames), set ops0.DeleteBin = 0. If you want to keep the tiffs, set ops0.RegFileTiffLocation to a file path.

**Comment by carlyrosewilling** [comment]
Thank you for your quick reply! However, the problem remains even with the readTiffHeader=0. I am wondering if perhaps the size of our files is too large?

**Comment by carsen-stringer** [comment]
It could be this if you don't have enough RAM on your computer, we load the full tiff by default. We plan to change this in the next week or so, but in the meantime you could split your tiffs.

**Comment by carlyrosewilling** [comment]
Okay thank you so much! I will try running it on a SCC to see if that remedies the problem for now.
