### ISSUE TITLE
where is wrapperOASIS?

### ISSUE THREAD

**Issue by Student213** [cortex-lab/Suite2P#108]
I dont have wrapperOASIS in my directory. I want to have the spike time and the deconvolved amplitudes, for this I  use deconvolution_3 and deconvType = OASIS. So where can i find wrapperOASIS?
Or is there an another method I can use for the spike time and amplitude?

with kind regards.

**Comment by Student213** [comment]
I dont have wrapperOASIS in my directory. In deconvolution_3 wrapperOASIS is needed if your deconvType = OASIS. where can i find wrapperOASIS?

**Comment by marius10p** [comment]
Please add the full Suite2p repository to your path. For example, addpath(genpath(PATH_SUITE2P)). That wrapper should be somewhere in the deconvolution subfolder.

**Comment by Student213** [comment]
Add the full Suite2P where, in the master_file?
```matlab
% check out the README file for detailed instructions (and extra options)
addpath('/home/mattijskuiper/Example') % add the path to your make_db file

%path to the OASIS
addpath(genpath('/home/mattijskuiper/OASIS'))

% overwrite any of these default options in your make_db file for individual experiments
make_db_example; % RUN YOUR OWN MAKE_DB SCRIPT TO  RUN HERE

ops0.toolbox_path = '/home/mattijskuiper/Suite2P-master';
if exist(ops0.toolbox_path, 'dir')
	addpath(genpath(ops0.toolbox_path)) % add local path to the toolbox
else
	error('toolbox_path does not exist, please change toolbox_path');
end

```
there is already a path to my Suite2P.

When I search [wrapperOASIS](https://github.com/cortex-lab/Suite2P/search?utf8=%E2%9C%93&q=wrapperOASIS&type=) I get one result.

**Comment by carsen-stringer** [comment]
sorry, that is an old function. Currently we run add_deconvolution which calls wrapperDECONV.m. If 'OASIS' is chosen then it calls OASISpreprocess. If you want to run the deconvolution without suite2p, then you can just put your traces and your neuropil directly into wrapperDECONV (with the options structure that you can see in add_deconvolution)
