### ISSUE TITLE
Tiff-files.

### ISSUE THREAD

**Issue by Student213** [cortex-lab/Suite2P#109]
Is there a script in Suite2P which makes tiffstack or files which can be used for Suite2P-pipeline?

for creating a tiffstack now I use this code (which was given to me by my tutor):
```matlab
%% load files
load('mouse10depth200green.mat')
%% scale factors
FileTifgreen='/home/mattijskuiper/PROPS/mouse10depth200green.tif'; %destination mane
chafa=zeros(numel(green),1);
chofo=zeros(numel(green),1);
for i=1:numel(green)
            chafa(i)=min(green{i}(:));
            chofo(i)=max(green{i}(:));
        end
mgreen=min(chafa);
magreen=max(chofo);
%%
tic
imwrite(uint16(green{1}+mgreen), FileTifgreen)
for k = 2:numel(green)
                imwrite(uint16(green{k}+mgreen), FileTifgreen, 'writemode', 'append');
end
toc
```
and the result looks like this:
![image](https://user-images.githubusercontent.com/33723765/33078083-eccb7782-ced1-11e7-9bc8-dde947530e8e.png)

I think this isn't good. A reason for this thought is, when it is running through the script 'eigs' it gets stuck in a loop and doesn't do anything besides looping around in eigs (between the lines 900 and 950). This probably due to the information it gets from 'get_svdForROI', because here:
```matlab     
mov             = bsxfun(@rdivide, mov, sdmov(:));
```
it get a lot of NAN's which makes it impossible to continue in eigs, I think.
I have the feeling it is the above script, for creating a tiffstack, that is messing up my data. 

another question. 
how do i figure out what my diameter is supposed to be?

with kind regards.

**Comment by carsen-stringer** [comment]
I think your tiff writing script is writing tiffs in the correct format. However, the scaling may not be good. If the image values are very small, they may all be rounded to zero (uint16 is integers from 0-2^16). Our tiffs from scanimage are from 0-2^13. You may want to try rescaling your images before converting them to uint16 (e.g. divide by the max across all frames and multiply by 2^13).

The diameter should be what you think the diameter of the cell is in pixels. You can look at the mean image of in one of these tiffs and see approximately how big your cells are, it doesn't have to be exact.

**Comment by Student213** [comment]
I will try to rescale the data.
To give you more insight in my data: 
The data i have is from CRCNS (dont know if you heard about them), i downloaded red and green, they are from the same experiment and depth. 
Green has maximum value of 2048, and minimum value of -440.
while red maximum value is 1576, and minimum value is -201.

if I use green.tiff, I get stuck in 'run_pipelin'->'sourcery'->'get_svdForROI'->'eigs'. In eigs it is looping around doing nothing between lines 900 and 950. This has to do something with the NAN's in 'ishermA', but IshermA gets his value of 'mov' which starts in get-svdForROI at line 50 where the 'bsxfun' is used. I know why I get the NAN's here, because it is dividing 0/0.
I dont have this problem with red. 

So i downloaded more content of CRCNS, the same thing happens with the green_file and not with red.

do you have these kind of problems, perhaps you know why this occurs?

with kind regards.

**Comment by carsen-stringer** [comment]
Instead of just adding the minimum try adding a bit more to the baseline, so you don't have zeros everywhere? In addition to scaling the pixels more to the 1-8000 range
