### ISSUE TITLE
wrapperDECONV not returning spikes

### ISSUE THREAD

**Issue by delrosni** [cortex-lab/Suite2P#110]
Hi Marius, 

After running wrapperDECONV on my processed somatic traces, I get results that look similar to my original raw trace:

![exproblemtraces](https://user-images.githubusercontent.com/8440743/33748816-84a53890-db7f-11e7-8c10-589f09370e68.PNG)

I have added OASIS to the path and ran the OASIS setup script. I specified my sensor tau (0.5) and frames per second (3.7) in the ops structure.  Interestingly, when I run OASIS's deconvolveCa wrapper with just the method specified as 'constrained_foopsi', I get spikes that look more reasonable.  

**Not relevant but for a spatial reference**, the trace I'm showing is from the selected cell: 

![exproblemmean](https://user-images.githubusercontent.com/8440743/33748942-28505880-db80-11e7-8e39-9ab08d77d9f9.PNG)
![exproblemroi](https://user-images.githubusercontent.com/8440743/33748944-2a37a52c-db80-11e7-97a2-31dcd353d5de.PNG)

**Comment by marius10p** [comment]
Hi,

Given your tau (0.5 seconds) and frame rate (3.7Hz), you should expect transients to decay in  ~2 frames, which is much faster than the apparent decay. Your transients seem to last for ~20-30 frames.  Either your timescale is not really 2 frames, or you have bursts of sustained activity, in which case the result is correct.

**Comment by carsen-stringer** [comment]
Did changing the timescale help? Please reopen this issue if you're still having problems with this, thanks
