### ISSUE TITLE
Lack of spike time and amplitude in F.mat

### ISSUE THREAD

**Issue by carlyrosewilling** [cortex-lab/Suite2P#113]
Hello! 

I am working on visualizing the data following spike deconvolution, and my F.mat data file seems to be lacking spike times and amplitude for each ROI. Is there a particular setting which needs to be specified in order for these variables to be collected?

Thank you in advance!

**Comment by carsen-stringer** [comment]
You will only get the deconvolved spikes if you run "add_deconvolution(ops0, db)" after "run_pipeline(db,ops0)". Did you run this step? If so, the traces are saved in the cell structure "sp"

**Comment by carlyrosewilling** [comment]
Hi Carsen, I do have this step, using OASIS, but whenever I load the F.mat and regops file, no data "sp" is returned.

**Comment by carsen-stringer** [comment]
are you sure that after you run add_deconvolution that the F*.mat file is changing? check that it's being modified. I'm not sure I've seen this issue before

**Comment by carsen-stringer** [comment]
please reopen this issue if you're still having problems, thanks
