### ISSUE TITLE
Numbering of ROIs on GUI

### ISSUE THREAD

**Issue by carlyrosewilling** [cortex-lab/Suite2P#115]
Hello there, it's me again with another question--

I was wondering if it is possible within the GUI to see the number of the cell? When I plot some fluorescent traces, I notice that some of the traces are very noisy and would like to look at the individual cell within the GUI, however, I just know generally where the cell is and it's index. Is there a better way to approach this/identify cells based on index?

Thank you in advance!

**Comment by carsen-stringer** [comment]
this was added a while ago, sorry I didn't comment on this sooner, it's located where the statistics about the cell are given and labelled as "cell #X"
