### ISSUE TITLE
File order change

### ISSUE THREAD

**Issue by scottcanoe** [cortex-lab/Suite2P#116]
Can I recommend that tiffs are loaded in human-sorted order? It took me a long time to realize that my tiffs were being loaded in like '1.tiff', '10.tiff', '100.tiff', etc., and I know I'm not the only one. Here's a fix: [sort_nat](https://www.mathworks.com/matlabcentral/fileexchange/10959-sort-nat--natural-order-sort)

**Comment by marius10p** [comment]
Yes, that's a good idea. Thanks for the link, we'll implement that shortly.

**Comment by scottcanoe** [comment]
Great, thanks. Much appreciated.

**Comment by carsen-stringer** [comment]
I've added sort_nat to build_ops3.m (where the file lists are populated), sorry for the delay!
