### ISSUE TITLE
Too many ROIs detected

### ISSUE THREAD

**Issue by MarioDipoppa** [cortex-lab/Suite2P#118]
Suite2p crashes at sourceryAddon (line 31):
Usub = Ucell(:, ipix)+ codes(j, :)' * mLam(ipos,j)';
[in sourceryAddon, in sourcery]
since it detects 21776 ROIs while mLam has size 10000 (its second dimension). I guess the issue is that there have been detected too many small ROIs. The number of ROIs grows quite quickly in the beginning:
848 total ROIs, err 0.5963, thresh 0.0408 
1602 total ROIs, err 0.5919, thresh 0.0408 
2303 total ROIs, err 0.5878, thresh 0.0408 
3000 total ROIs, err 0.5835, thresh 0.0408 
....
after 16 iterations:
10524 total ROIs, err 0.5383, thresh 0.0408
....
and at last:
21776 total ROIs, err 0.4854, thresh 0.0408

**Comment by carsen-stringer** [comment]
are the ROIs okay? did you try setting a threshold on the number of iterations or the convergence criterion?

**Comment by carsen-stringer** [comment]
is this still a problem Mario? if not please close the issue
