### ISSUE TITLE
neuropil subtraction with small ROIs

### ISSUE THREAD

**Issue by ransona** [cortex-lab/Suite2P#119]
Hi
Thanks for developing this brilliant pipeline. I'm experiencing a bug with extracting rois from bouton data that specifically comes up when I set db(i).diameter < 5. It seems to be related to the neuropil extraction or subtraction as if I get it with ops0.signalExtraction = 'surround' but not with 'raw' or 'regression'. It throws the following error:

715 total ROIs, err 0.4588, thresh 0.0190 
1190 total ROIs, err 0.4512, thresh 0.0190 
1363 total ROIs, err 0.4483, thresh 0.0190 
1415 total ROIs, err 0.4474, thresh 0.0190 
1415 total ROIs, err 257248016.0000, thresh 0.0190 
1415 total ROIs, err 256747776.0000, thresh 0.0190 
1415 total ROIs, err 256708928.0000, thresh 0.0190 
Error using bsxfun
Non-singleton dimensions of the two input arrays must
match each other.

Error in svdecon (line 36)
        V = bsxfun(@(x,c)x./c, V, s');

Error in extractSignalsSurroundNeuropil2 (line 95)
[u, s, v] = svdecon(ratCS);

Error in run_pipeline (line 78)
                [ops, stat, Fcell, FcellNeu] =
                extractSignalsSurroundNeuropil2(ops,
                stat);

Error in master_file_AR1 (line 83)
    run_pipeline(db, ops0);
 
36          V = bsxfun(@(x,c)x./c, V, s');

Thanks
Adam

**Comment by carsen-stringer** [comment]
sorry this code is actually our "automatic" drift detection (it computes the ratio between the inner pixels of the cell and the outer pixels - if they change non-uniformly then it suggests drift). I think your boutons are too small for this to work, I've added an option to shut this off (by default it's off). The option is ops.getZdrift.

**Comment by ransona** [comment]
ah I see, thanks for sorting it!
