### ISSUE TITLE
GetRandFrames when not using standard folder structure

### ISSUE THREAD

**Issue by ransona** [cortex-lab/Suite2P#120]
Hi again,
I've run into what seems to be another small bug which comes up on line 75 of GetRandFrames (if ismember(ops.expts(k), getOr(ops, 'expred', []))) if you try to run registration when you've provided the full path to the tif files. i.e. with a make_db as below, which was adapted from one of the examples:

db(i).mouse_name    = 'notImportant';
db(i).date          = '2016';
db(i).expts         = []; % leave empty, or specify subfolders as numbers
db(i).diameter      = 12;
db(i).RootDir       = 'E:\DataTemp\CFAR075\2016-10-12\2'; % specify full path to tiffs here

The error it gives is:
Reference to non-existent field 'expts'.

Error in GetRandFrames (line 75)
        if ismember(ops.expts(k), getOr(ops, 'expred',
        []))

Thanks
Adam

**Comment by horsto** [comment]
Same issue here. 
`db(i).expts = []; % leave empty, or specify subfolders as numbers
`
db.expts cannot be empty.

**Comment by carsen-stringer** [comment]
thanks for pointing this out, it's been fixed now, let me know if it still gives you problems

**Comment by ransona** [comment]
great thanks, will give it a try.
