### ISSUE TITLE
Syntax error in cellDetection/compute_overlaps.m

### ISSUE THREAD

**Issue by fralik** [cortex-lab/Suite2P#124]
There is a syntax error in file cellDetection/compute_overlaps.m on [line 23](https://github.com/cortex-lab/Suite2P/blob/2d2b3e4663b55bc4ec611fee67f399d6802a7638/cellDetection/compute_overlaps.m#L23).

**Comment by carsen-stringer** [comment]
Thanks for pointing that out, I don't think that function is being used anymore, let me know if you got an error with it. In the standard pipeline we compute overlaps during signal extraction in signalExtraction/getNonOverlapROIs.m

**Comment by fralik** [comment]
Yes, there is an error with it. I guess it is better to delete it since it is not used (and can't be used in it's current version).
