### ISSUE TITLE
Missing Fbase when L1 option is chosen

### ISSUE THREAD

**Issue by subroutines** [cortex-lab/Suite2P#126]
In `wrapperDECONV` when you choose the `OASIS` option, the `OASISpreprocess()` function returns a variable called `Fbase`, but when you choose the `L1` option the function does establish this variable. Several lines later `Fbase` is a required input for a `bsxfun` call, and thus results in an error when using the `L1` option...

```matlab
switch getOr(ops, 'deconvType', 'OASIS')
    case 'OASIS'
        [sp, ca, sd2, Fbase] = OASISpreprocess(ops,  Fsub);
    case 'L0'
        [sp, ca, sd2] = deconvolution_standalone(ops, Fsub);
end
```

`baselines = bsxfun(@times, mean(Fbase,1), sd);` :warning:

https://github.com/cortex-lab/Suite2P/blob/2d2b3e4663b55bc4ec611fee67f399d6802a7638/SpikeDetection/wrapperDECONV.m#L94

**Comment by marius10p** [comment]
Sorry, I broke that temporarily with an update but it should be working now.

**Comment by carsen-stringer** [comment]
please reopen if there are still issues with this, thanks
