### ISSUE TITLE
issue in dat.stat

### ISSUE THREAD

**Issue by YGUO29** [cortex-lab/Suite2P#129]
Hi! I just started using this toolbox and was trying to figure out the output structures... 
It seems the array in dat.stat.ipix is not the actual linear indecies of the ROIs... it's different from what I got with sub2ind(imagesize, xpix, ypix).
Also the dat.stat.lambda and dat.stat.lam seem to be identical (both not normalized from 0 to 1)

Can you tell is there anything I might be doing wrong? Thanks!

**Comment by carsen-stringer** [comment]
Try sub2ind([numel(dat.ops.yrange), numel(dat.ops.xrange)], ypix, xpix). The pixels of the cell are defined in the subregion of the image that was cropped during registration.

Sorry lam and lambda are the same now in the pipeline.

**Comment by YGUO29** [comment]
Got it. Thank you!

**Comment by johannasiglgloeckner** [comment]
I am having a similar issue.  I am trying to assign the output traces to the cells within the max projection, i.e. which cell belongs to which trace. But I dont know how to do that with the ypix,xpix because its defined by the subregion.... any hints? thanks :)

**Comment by carsen-stringer** [comment]
I'm closing this, please reopen it if there are still issues
