### ISSUE TITLE
Potential bug in openBinFiles

### ISSUE THREAD

**Issue by fralik** [cortex-lab/Suite2P#131]
Seems like a potential bug to me in file openBinFiles on line [9](https://github.com/cortex-lab/Suite2P/blob/2d2b3e4663b55bc4ec611fee67f399d6802a7638/registration/openBinFiles.m#L9). Variable `xFOVs` is not defined in that function and it is not a function itself.

**Comment by carsen-stringer** [comment]
Oops thanks for that. Are you trying to run with interpolation across planes? What that means is the registration aligns the mean images across planes in Z. xFOVs is used to split up the FOV into multiple sections, sorry I've never tested these options together (we don't use the interpolation ourselves) and missed this. What kind of data are you trying to process? Maybe I can help you with the settings?

**Comment by fralik** [comment]
Not really. I am working on a version of Suite2P that decouples the file structure from the code, i.e. so it is possible to have different storage schemas. Would like to make it backwards compatible, so that you could perhaps merge it into the main source code.
For that, I am going through Suite2P and trying to understand it.

**Comment by carsen-stringer** [comment]
Awesome! That sounds really useful. Right now the code is messiest in the registration because there are many different options, in particular to run with multi-plane imaging, which may not be necessary for all users.

**Comment by carsen-stringer** [comment]
We've added an option in the python version to run a user-specified clean-up script at the end of the pipeline. You could use this script to for instance copy binary files to certain locations that you want, which might address what you're trying to do
