### ISSUE TITLE
Unused functions

### ISSUE THREAD

**Issue by fralik** [cortex-lab/Suite2P#133]
It seems that there are quite a few unused functions in the package. Just to list some of them:

- cellDetectionStandalone
- fastClustNeuropilCoef (not even a function).
- fast_clustering
- fast_clustering2 (not even a function).
- fast_clustering_with_neuropil
- fast_clustering_with_neuropil2
- add_Zcorrection

I do not see any reference to these files from any other files. Is the intention of having these functions that people can use them outside Suite2P package? Or is it safe to remove those functions?

**Comment by marius10p** [comment]
Some of these are used externally and others have been part of the clustering algorithm in the past but not entirely superseded by the new algorithms. We are about to make another big update to the clustering approach, which is when we'll consider removing some of these.
