### ISSUE TITLE
Regarding post-processing of Fcell traces

### ISSUE THREAD

**Issue by hamutoro** [cortex-lab/Suite2P#135]
I have 2 questions regarding the output dat.Fcell:

1) is the latest package giving us Fcell neuropil-corrected, i.e is Fcell = uncorrected F - c * FcellNeu? or do we have to compute Fcell - c*FcellNeu to obtain the neuropil-corrected traces?

2) how 'raw' are the traces stored in Fcell? If I want to do my own subsequent pixel normalization and baseline normalization (to obtain dF/F), do you recommend that I work with Fcell, or other outputs upstream of Fcell that are less processed? I am using the 'surround' extraction option. 

Thanks in advance!

**Comment by carsen-stringer** [comment]
Sorry for the delay in responding! 

1. Fcell is NOT neuropil-corrected at all. You are correct:
Fcorrected = Fcell - c*FcellNeu.

2. The traces in Fcell are the multiplication of the cell mask weights with the raw pixel values in each frame. The cell mask weights are given by stat(j).lam and the pixel locations by stat(j).ypix,stat(j).xpix. The surround neuropil (FcellNeu) is also just a summation of the raw pixel activity surrounding the cell (each pixel has equal weight).

**Comment by carsen-stringer** [comment]
I'm closing this, please reopen this if you have more questions :)
