### ISSUE TITLE
Threshold Issue with GUI2p

### ISSUE THREAD

**Issue by pratikmistry08** [cortex-lab/Suite2P#138]
Hi,

When I try to load the data file into the GUI, I get the following error, and the GUI remains blank. I have paths to all the Suite2P functions, and I'm getting this error after running the software with the provided example dataset.

Reference to non-existent field 'threshold'.

Error in classROI (line 32)
   stat(j).iscell = Ypred(j) > h.dat.cl.threshold;

Error in new_main>pushbutton17_Callback (line 79)
    h                   = classROI(h);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in new_main (line 17)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)new_main('pushbutton17_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.

**Comment by carsen-stringer** [comment]
I'm sorry for the delay in responding. It may have been because we changed the output format, I have changed it back to the way it used to be, let me know if this fixes your problem. Please pull the latest version of the code.

**Comment by carsen-stringer** [comment]
Not a problem, sorry for the bug!
