### ISSUE TITLE
where are manually curated ROIs saved?

### ISSUE THREAD

**Issue by marinafridman** [cortex-lab/Suite2P#142]
Hi!

I wanted to make sure I am selecting the correct, manually curated cells after running the GUI. I've been using the labels in dat.stat.iscell, based on what I read in the readme, but I get some cells where the Fcell is zero at times, which is strange... Now I found a note at the end of the master file example script that says 
>>% manual, GUI overwritten "iscell" labels are in dat.cl.iscell

However I do not see an iscell field in the dat.cl structure. 

What should I be using for the iscell label after manual curation?
Many thanks!
~Marina

**Comment by carsen-stringer** [comment]
Sorry Marina, that note is incorrect. You are right that the manual labels will be saved in "stat(i).iscell" where i is the index of the cell. You can make it into an array by saying 
~~~
iscell = [stat.iscell]
~~~
Also, make sure you are loading the F*_proc.mat files - this is where the manual labels are saved after clicking (although I think you already are if you see a "cl" field).
