### ISSUE TITLE
Processing extracted red channel 

### ISSUE THREAD

**Issue by kameronclayton** [cortex-lab/Suite2P#146]
The REDBinary file is useful for extracting red channel fluorescence traces using cell masks and weights. Would you recommend applying a  neuropil correction to the red ROIs once extracted?  Not sure if the spatial correlation structure would be the same in a stable fluor channel as a GCaMP channel...

**Comment by carsen-stringer** [comment]
I wouldn't expect this to be necessary unless you're seeing a lot of bleedthrough from the GCaMP into the red channel

You can check the bleedthrough levels for instance by regressing the mean green image onto the mean red image and seeing how large this regression coefficient is
