### ISSUE TITLE
generate target frames

### ISSUE THREAD

**Issue by annie2013** [cortex-lab/Suite2P#155]
Regarding generation of the target frame that you generate at the beginning, is there a way that I can specify which frames that I use to generate that, for example, preselect the frames when the mouse sits still or is less active, and use them to generate the target frame.

**Comment by marius10p** [comment]
No, sorry. I wouldn't recommend doing that anyway, you might get poor registration in other parts of the movie if your target does not sample all activity patterns sufficiently.

**Comment by marius10p** [comment]
Let us know if this is still a problem, closing issue for now.
