### ISSUE TITLE
Change the brightness of the mean image in GUI

### ISSUE THREAD

**Issue by PhantomSpike** [cortex-lab/Suite2P#158]
Hi,

Firstly, thank you very much for developing this excellent tool.

I have a simple question regarding the mean image that appears in the GUI. Somehow, the brightness is a bit too much and it is harder to select the cells (see attached eg). Is there any way of adjusting the brightness of the image that is displayed by the GUI?

A second note, which is more of a suggestion rather than an issue. It is a bit difficult when you have to constantly switch between the mean image and the ROI mask. It would be great if the ROIs could be displayed directly onto the mean image, rather than having to toggle between them. An even better implementation would be if the ROI mask was transparent and only the outline was visible. In this way you could really see the overlap between the ROI mask and the actual cell on the image. Not sure how long it will take to implement something like this but it would of great help.

Thanks again and looking forward to your reply.

Best wishes,

Alex

![screenshot from 2018-12-02 18-31-40](https://user-images.githubusercontent.com/23742907/49343413-bd6b0180-f660-11e8-9ece-4b4636abc90a.png)

**Comment by PhantomSpike** [comment]
Actually, proc(p) does something very similar to what I would like. :)

**Comment by carsen-stringer** [comment]
Hey Alex,

If you're just getting started with suite2p, I'd highly recommend using the python version - it has more features and the GUI is much MUCH better (https://github.com/MouseLand/suite2p). It in fact has the overlay view that you're looking for. Also you can run the pipeline directly in the GUI. And you can save the output of the pipeline as a matlab file. 

Here's the wiki page on the GUI, where you can see all the features it has (that will not be added to the matlab version--it's too difficult): https://github.com/MouseLand/suite2p/wiki/Using-the-GUI

Best,

Carsen

**Comment by PhantomSpike** [comment]
Hi Carsen,

Thank you very much for your reply.

I tried the Python version and it is SO MUCH better. It was like going from an old car to a Ferrari. Thank you so much for developing the code, it is amazing. :)

I have just a few quick questions. I will ask you here because I think it doesn't deserve a separate issue in the Python page, it is just me being a noob in Python and the software.

1. Run together multiple presentations in the same FOV

In our experiments we typically present several different stimuli in the same area (FOV), e.g. stim1, stim2, stim3.

How should I run the Python GUI such that they are processed together i.e. registered together and have the same ROIs across the different stimuli?

Currently I have the following structure Animal/AreaX/stim1..stimN where stim are folders containing the .tiff files for each stimulus. I then do 'Add directory to data_path' selecting AreaX and also select look_one_level_down = 1.

Is this the right way of doing it, or the order of the .tiff files will be scrambled? How should I name my stim folders such that they are processed in the right temporal order?

Is there a parameter I can specify to keep the traces from the different stims separate or they will be always concatenated? This can also be potentially a problem for the deconvolution as there is a bit of a pause between stim(n) and stim(n+1) so they are not continuous in time.

2. Run several areas together

Now imagine that I want to run for 1 given animal, 3 different areas Area01,02 and 03 which each have stim1 and stim2. Should I have 3 different folders Area01-03, in each one two subfolders stim1 and stim2 having the .tif files? Then I add the 3 Areas folders separately using Add directory... button and select look_one... = 1. 

3. Saving selected ROIs

After I have clicked the ROIs in the GUI into cells/not cells are they saved automatically in the .npy files or I need to do something? Is the variable 'iscell' in the .mat file updated too or not? 

Sorry for the long tread and if my questions are silly. Thanks again for your help!

Best,

Alex

**Comment by PhantomSpike** [comment]
Hi,

I raised the same issues on the Python page as they seemed like genuine problems rather than just me being incompetent in Python haha.

Maybe it is better if you reply there.

https://github.com/MouseLand/suite2p/issues/126

https://github.com/MouseLand/suite2p/issues/127

Thanks!

**Comment by carsen-stringer** [comment]
Glad you like the python :D yeah these are all good questions (question 3 has been asked many times so I def need to add it to the documentation). I'll answer there and close this issue

**Comment by carsen-stringer** [comment]
Also here's the answer to number 3: https://github.com/MouseLand/suite2p/wiki/Outputs#matlab-output
