### ISSUE TITLE
Correct values for ops0.sensorTau?

### ISSUE THREAD

**Issue by PhantomSpike** [cortex-lab/Suite2P#159]
Hi,

Apologies if this has been answered elsewhere (couldn't find it in the other issues).

When you choose the decay values for the sensors (GCaMP6f, m and s), what are the "correct" values to input in the parameter ops0.sensorTau?

From this paper: https://www.biorxiv.org/content/early/2017/06/27/156786 which talks about Oasis it says that: 

"Instead, we fixed the timescales of the calcium kernel to be approximately the measured values from the literature11–13 (Figure 1c, “+fixed taus”). For simplicity, we divided all sensors into a fast, a medium and a slow category, and used timescales of 0.5, 1 and 2 seconds for the three categories. As we show below, the precise values for these timescales were not critical."

If I understand correctly, does this mean that ops0.sensorTau should be set to 0.5s for 6f, 1s for 6m and 2s for 6s or I should use the actual values from the original GCaMP6 paper https://www.nature.com/articles/nature12354 ? If you use the values from the paper, what are the actual values you use?

From reading the bioarxiv paper it seems that it doesn't matter too much anyway, but just wanted to make sure that I am doing the right thing. 

@marius10p 

Thanks!

**Comment by marius10p** [comment]
Sorry, those were incorrect in the preprint, I'll update it. The [published version](http://www.jneurosci.org/content/38/37/7976) has the actual values we used:

"The timescale of the exponential was chosen as 1 of 3 possibilities: fast (0.7 s), medium (1.25 s), or slow (2 s), according to the calcium sensor used. Timescales for the GCaMP6 sensors were assigned according to their version. For other sensors, timescales were assigned based on the literature (OGB: medium; GCaMP 5k: fast; jRCaMP1a: slow; jRGECO1a: fast)."

I remember choosing these a long time ago as the rounded average of the respective sensors that fall into each category, but taking into account the fact that multiple APs generally lengthen the timescale (so don't use the single AP kernels which are overly optimistic).

**Comment by PhantomSpike** [comment]
Hi @marius10p,

Thank you for the quick response! Just to make sure I've understood correctly, you would recommend setting ops0.sensorTau to: 

- 0.7s for GCaMP6f
- 1.25s for GCaMP6m
- 2s for GCaMP6s

OR you are saying that even those are an underestimate and I should use even longer ones?

Thanks!

**Comment by marius10p** [comment]
Sorry, I meant those are what we actually used. 

What I meant is, if you asked someone "what is the timescale for gcamp6f", they might quote you something shorter, like 0.3 or 0.5, because that's the single AP decay timescale.

**Comment by PhantomSpike** [comment]
Super, thanks a lot. Everything is clear now :)
