### ISSUE TITLE
Redefine channel order

### ISSUE THREAD

**Issue by OmriG87** [cortex-lab/Suite2P#162]
I have many large tiff files that I would like to run through the suite2p pipeline.
However the stable red channel is channel 1 and the functional green channel is channel 2.
The assumption for registration is that the red channel is last.
Is there a way to overcome this?

**Comment by carsen-stringer** [comment]
You have set ops.AlignToRedChannel = 1 and it does not work? In theory it should work (also set ops.gchannel=2 and ops.rchannel=1 and ops.nchannels_red=2). 

It definitely works in the python version - and if you're just getting started with suite2p I'd highly recommend using that over the matlab - we are no longer updating the matlab version. the option is 'align_to_chan': https://github.com/MouseLand/suite2p/wiki/Registration. Also you don't need to be familiar with python, you can run the pipeline through the gui: https://github.com/MouseLand/suite2p/wiki/Run-the-pipeline

**Comment by OmriG87** [comment]
Thank you, this worked.
I rather keep working with the MATLAB version for now but I will keep in mind the option to switch.
