### ISSUE TITLE
Registration and Example data

### ISSUE THREAD

**Issue by elgutierr** [cortex-lab/Suite2P#165]
Hello,

In the registration step, is it possible to save all registered tiffs? Right now it seems that only a sample of them are saved (e.g. 5/50 of the example data).
I was also wondering if it would be possible to have more details on the example data - recording time, frame rate etc - to compare to our data.

Thank you for your help!

**Comment by carsen-stringer** [comment]
It should be saving all of them, can you check if there are more frames in the saved tiffs than the original tiffs? I think suite2p saves 2000 per tiff by default.

It is GCaMP6s data with 2P recording. If you're just starting out with suite2p I HIGHLY recommend the python version. The registration is better (and we've added options to help with 1P data) and you can look at these registration metrics we compute to see where the algorithm is failing.

**Comment by elgutierr** [comment]
Our data is 2 minutes recordings (584 frames, which are saved as 1 per TIF file). Is there a way to change the default setting on the matlab version?

Thank you for your help!

**Comment by carsen-stringer** [comment]
You can change this line here: https://github.com/cortex-lab/Suite2P/blob/f482cfb8e1c62e291bd11132250b0304a8323600/readWrite/write_reg_to_tiff.m#L15

Change that number to 584 instead of 2000, and each tiff will be the same length as your original tiffs when you run the pipeline.

**Comment by elgutierr** [comment]
That worked, thank you!
