### ISSUE TITLE
Retrieve neuropil basis function

### ISSUE THREAD

**Issue by lfederico** [cortex-lab/Suite2P#17]
It would be useful to retrieve the traces and the maps of the basis functions used to model the neuropil. It would allow to make maps of neuropil-only responses. Is this info already available somewhere in the dat structure? Thanks, Federico

**Comment by marius10p** [comment]
With ops.saveNeuropil = 1, you now get a new file NEU_.... for each plane, containing the neuropil spatial basis functions (S) and their timecourses (Ntraces).
