### ISSUE TITLE
Enquiry regarding diameter of ROI

### ISSUE THREAD

**Issue by xwchia** [cortex-lab/Suite2P#178]
Hi, 

First and foremost thank you for the wonderful tool that you have provided!

We have a question regarding the **Diameter parameter** in the suite2p GUI.

Before updating the suite2p version, we had to input 2 different values for the Diameter parameter, taking into account the aspect ratio.

However, for the current version, there is an additional Aspect Ratio parameter to key in. Is it safe to assume that i no longer have to input 2 different values for Diameter as the programme will automatically take into account the Aspect Ratio that we entered?

Thank you. Appreciate any kind guidance regarding this matter.

**Comment by carsen-stringer** [comment]
can you please post this on the python version and I'll answer it there www.github.com/mouseland/suite2p

the short answer is yes it's only the aspect ratio that is used
