### ISSUE TITLE
Neurofinder

### ISSUE THREAD

**Issue by syncrostone** [cortex-lab/Suite2P#18]
This isn't really an issue, but wanted to let you know that I ran your algorithm on the neurofinder datasets and uploaded the results. We ran it with all the defaults but no registration or deconvolution, and thresholded using the standard deviation of the traces. 

Your algorithm is currently doing the best! If you want to discuss, feel free to open an issue on the [neurofinder](https://github.com/codeneuro/neurofinder) repo.

**Comment by marius10p** [comment]
It's great that you guys did this. Let's continue the conversation in your repo.

**Comment by marius10p** [comment]
@syncrostone regarding what parameters to use for a relatively short recording, the following should all be scaled down by the same factor

ops0.Nk0                     = 1300; % initial number of clusters
ops0.Nk                       = 650;    % final number of clusters
ops0.nSVDforROI        = 1000;   % number of SVDs kept for ROI detection

We use these settings for recordings with 100 to 500 cells. I would decide the exact factor (1/2, maybe 1/4?) based on the training data. You can load the Suite2P result file in the GUI to check if cells have been over/under segmented. I could take a look at some of the training datasets. 

It's also important to approximately set the expected cell diameter for each FOV.  It tolerates a factor of 2 mismatch, but not much more than that

clustrules.diameter      = 10; % expected diameter of cells (used for 0.25 * pi/4*diam^2 < npixels < 10*pi/4*diam^2)

**Comment by syncrostone** [comment]
@marius10p I was plotting the data, and the cells looked right sized and not over/under segmented. There are approximately 300 cells in each ground truth set, so I don't think we need to change those factors? Does that sound right? 

Or should we change them because the dataset is shorter? I'll post a screenshot from one of the datasets once we have the new data on the website.

**Comment by marius10p** [comment]
I have run neurofinder data in the past with Suite2P and I remember over-segmentation problems at the default settings. I think it would have at least been a problem with the old 1-2 minute datasets. Not sure how you are plotting the data, but it was immediately obvious in the suite2P GUI that relatively few cells were active and detected by the algorithm (of the ~300 in the ground truth), and I saw over-segmentation.

**Comment by syncrostone** [comment]
Oh! I dealt with that by thresholding by standard deviation of each neuron after the fact and eliminating empty neurons. Changing those numbers will fix and eliminate the need to threshold?

**Comment by marius10p** [comment]
Thresholding on the variance has never worked well for me. I think it has to do with non-homogeneous variance over the field of view, and more importantly neuropil contamination. I would try a smaller number of clusters on this kind of data, and then still applying a (low) threshold, because many ROIs are neuropil.

**Comment by marius10p** [comment]
I think it's best if I make my own submission to the challenge, once I add to Suite2P the features which the challenge requires, like pixel trimming. Thanks @syncrostone for making the initial submission, I appreciate it!
