### ISSUE TITLE
provide standalone function for cell detection only 

### ISSUE THREAD

**Issue by marius10p** [cortex-lab/Suite2P#19]
It would take as input raw data from RAM, and output ROIs and timecourses. 

@syncrostone  This could be used to measure the run time of Suite2P for cell detection only.

**Comment by syncrostone** [comment]
That'd be awesome!

**Comment by marius10p** [comment]
I have implemented the standalone version

[stat, F, Fneu] = cellDetectionStandalone(dat, ops);
