### ISSUE TITLE
Support for separate Tiffs

### ISSUE THREAD

**Issue by syncrostone** [cortex-lab/Suite2P#23]
It'd be really useful if there were support for lists of tiff files that are individual images rather than image stacks. Doing the conversion manually can be very time consuming, even on 3000 frames. With the bigger datasets, it becomes prohibitive.

**Comment by marius10p** [comment]
Now works for separate tiff files. Use a db entry like this to bypass folder structure requirements

% example for datasets without folder structure
db(i).mouse_name    = 'notImportant';
db(i).date          = '2016';
db(i).expts         = []; % leave empty, or specify subolders as numbers
db(i).diameter      = 12;
db(i).RootDir       = 'F:\DATA\neurofinder\neurofinder.01.00\images'; % specify full path to tiffs here
