### ISSUE TITLE
Bug in new_main

### ISSUE THREAD

**Issue by MarioDipoppa** [cortex-lab/Suite2P#26]
I got the following bug:
Reference to non-existent field 'region'.
Error in get_parent_stats (line 6)
        h.dat.stat(i).V         = sum([h.dat.stat(i).region.V]);

I'm not sure where h.dat.stat(i).region should be computed in suite2P

**Comment by marius10p** [comment]
Since this bug does not usually happen, it would be a lot more helpful to describe if anything was done differently here, or if the results file looks strange in any way.

**Comment by marius10p** [comment]
those fields are no longer used. The new version should be more robust to these kinds of problems. Re-open issue if necessary.
