### ISSUE TITLE
spike time indexing

### ISSUE THREAD

**Issue by woodkath** [cortex-lab/Suite2P#27]
I have a problem with matching up the spike times/amps with the calcium traces... I selected cells using the GUI and plotted the Calcium traces (dat.F.Fcell{dat.cl.iscell}) and then I plotted with it the spike times/amps (dat.cl.dcell{dat.cl.iscell}.st), the spike times do not seem to line up well with my Ca2+ traces... is the indexing of the spike times different to the calcium traces? I have pasted some examples below (the Ca2+ trace is in grey @30fps and the spikes blue):
![image](https://cloud.githubusercontent.com/assets/17785260/19387520/aec4318a-91e8-11e6-8dfe-e58d7e08a478.png)

**Comment by woodkath** [comment]
I looked through all the traces and discovered that the indexing was a constant value off - this constant corresponded to the length of the variable dat.stat0.  So in order to find the spikes for a given ca2+ trace (dat.F.Fcell{dat.cl.iscell}) I subtracted this constant from the iscell values.  See below for same traces with corrected indexing (ignore the scaling in these figures):
![image](https://cloud.githubusercontent.com/assets/17785260/19393140/86550dc8-9201-11e6-82c6-32ce40cf0bdc.png)

**Comment by marius10p** [comment]
Hi,

Sorry for never getting back to this, it slipped under my radar somehow. We have made several big updates to make the whole pipeline more robust, including the spike deconvolution code. You will now find the result in stat(j).c and stat(j).st for each cell. I would be curious if you still get this strange issue. 

Best,
   Marius

**Comment by marius10p** [comment]
Oh, I understand the problem now. Indeed, the spikes were only computed for ROIs tentatively identified as possible cells. This excluded exactly the first Nk ROIs, which was the length of stat0. 

The pipeline has been reworked to only ever output tentative cells. So the indexing issue should no longer occur.
