### ISSUE TITLE
Classify somata and dendrites

### ISSUE THREAD

**Issue by MarioDipoppa** [cortex-lab/Suite2P#3]
It could be useful to classify somata and dendrites. Even if we use only somata for analysis, the dendrite ROIs could be subtracted from the neuropil masks. One possibility would be to put both somata and dendrites on the left, somata having warm colors and dendrites cold colors. To classify well dendrites it is probably necessary to well inspect the mean signal, therefore one could have three options for the field of views: only colored ROIs, only grey mean fluorescence and one additional image with mean fluorescence as brightness and ROIs as hue.

**Comment by marius10p** [comment]
I have tried the view with mean fluorescence and ROIs as hue and do not find that it works very well. Switching quickly between views seems to work better. 

Also, Suite2p now classifies somata based on anatomical criteria. Dendrites would be harder to classify, but can be done by the user based on output anatomical measures available in stat(icell) for each cell.
