### ISSUE TITLE
Documentation non-rigid registration 

### ISSUE THREAD

**Issue by noahpettit** [cortex-lab/Suite2P#30]
It would be great if you could include an example master_file.m for using non-rigid registration or expand the documentation to list what options need to be set for non-rigid registration to work. It's not clear what   values ops.splitBlocks or ops.splitTaper should take, and what additional options may need to be defined.

**Comment by marius10p** [comment]
Sorry for the delay, Noah, we were actually just in the process of updating that feature. Almost there, @carsen-stringer is making the update very soon.

**Comment by carsen-stringer** [comment]
The block registration is now defined in a simpler way, we assume that it will only be used in the direction of scanning (Y direction). As the microscope is scanning, the tissue can move continuously, this is the issue we're trying to correct for.

db(i).numBlocks defines to the number of blocks into which to split the frames (in the Y direction). 6 works well.

db(i).blockPixels defines the number of pixels in each block. If blockPixels * numBlocks > y-pixels, then the blocks will overlap. This will help with the estimation. I would recommend setting blockPixels > 100.

If you want to check how it's working, set ops.RegFileTiffLocation. Then the registered tiffs will be saved and you can see if the registration worked correctly on your data.

**Comment by xigumalu** [comment]
Can you please implement the possibility to split frames in x-direction as well, as was possible in older versions of Suite2P? I have made extensive use of this feature.
The assumption you are making is that the brain inside the field-of-view is always moving as one block (so to say), but due to the animal's movement different parts of brain may actually move into different directions (at least that's my experience), which makes it necessary to also correct in the x-direction.

**Comment by carsen-stringer** [comment]
Have you tried running with and without splitting in x-direction and compared the tiffs? I'm happy to add it back in, sorry I was basing my judgment on cortical recordings where I never saw independent x movement.

**Comment by xigumalu** [comment]
Yes, I've tried multiple ways of splitting (including not splitting at all) and always tried to settle on the minimum number of splits. But in many cases the splits in x-direction were very helpful. Yes, it's probably related to what brain region one is imaging.

**Comment by marius10p** [comment]
Hi Sylvia, have you tried the new version of non-rigid registration? Carsen made it significantly better than the old version, so it might work better than you remember it working, even without x-direction splits. -Marius
