### ISSUE TITLE
Folder structure for raw data

### ISSUE THREAD

**Issue by xigumalu** [cortex-lab/Suite2P#31]
I'm suggesting to make the expected path where to find the raw 2P data more flexible. Right now Suite2P expects the data in '...\<animal_name>\<date>\<experiment ID>. Instead one could define path components, like animal name, in the data base file, as is done already, and then specify the exact path made up of these components and possibly other folders inside the master file, which is defined by each user separately.

**Comment by marius10p** [comment]
This can now be achieved by setting RootDir outside of run_pipeline (either in ops or db). It will not be over-written, but if the field does not exist, the old method is used.

**Comment by xigumalu** [comment]
Could you please give an example of how the folder structure can be specified using this variable?
Let's say my raw 2P data is in:
...\Data\"animal_name"\"date"\2P\"experiment"
where everything in quotes will change from dataset to dataset.

**Comment by marius10p** [comment]
The idea here was that you specify yourself the full extent of RootDir, based on your own formatting requirements, which can change from person to person. You could do this in the master file, just before run_pipeline, or directly in your db file.
