### ISSUE TITLE
Errors when not using GPU

### ISSUE THREAD

**Issue by swift505** [cortex-lab/Suite2P#37]
Hello,
I've just started using your software and have encountered problems related to not having an Nvidia GPU (my machine has an AMD card).
In master_file I have set
    **ops0.useGPU = false**

So far I have encountered errors at two stages during registration, with **reg2P**.

***
ERROR 1::

Error using gpuDevice (line 26)
There is a problem with the CUDA driver or
with this GPU device. Be sure that you have
a supported GPU and that the latest driver
is installed.

Error in getBatchSize (line 3)
g = gpuDevice;

Error in register_movie (line 6)
nFramesPerBatch = getBatchSize(w*h);

Error in align_iterative (line 20)
    dreg  = register_movie(data, ops,
    dsnew);

Caused by:
    The CUDA driver could not be loaded.
    The library name used was 'nvcuda.dll'.
    The error was:
    The specified module could not be
    found.
***

This error occurs when **register_movie** calls **getBatchSize**, which in turn calls **gpuDevice**.
To temporarily get around this error I commented out the call to **getBatchSize** and set
**nFramesPerBatch = 2** in register_movie.

However, I then get a second error later in **reg2P**:

***
ERROR 2::
There is a problem with the CUDA driver or
with this GPU device. Be sure that you have
a supported GPU and that the latest driver
is installed.

Error in regoffKriging (line 128)
        dl   =
        gpuArray(single(-lpad:1:lpad));

Error in GetRegOffsets (line 13)
        [ds, Corr]  = regoffKriging(dat,
        ops1{i,l}, 0);

Error in reg2P (line 132)
            [dsall, ops1] =
            GetRegOffsets(data, j, iplane0,
            ops, ops1, yFOVs, xFOVs);

Caused by:
    The CUDA driver could not be loaded.
    The library name used was 'nvcuda.dll'.
    The error was:
    The specified module could not be
    found.
***

As far as I can see, the call to **gpuArray** in **regoffKriging** occurs whether or not useGPU is true.

Please advise.  Thanks very much for your help.

**Comment by marius10p** [comment]
@mkrumin the first of these errors was introduced by your update. Can you please let us know the best way to fix it?

**Comment by carsen-stringer** [comment]
I've fixed regoffKriging so that this line is in an if statement controlled by useGPU.

**Comment by marius10p** [comment]
I pushed a fix, should work fine now. Let us know if there is still a problem.

**Comment by mkrumin** [comment]
Hi Marius, thanks for doing that fix in register_movie.m
Without GPU the translation is running frame-by-frame in a loop, no matter
what the nFramesPerBatch is. For better readability of the code, I would
suggest setting it to either 1, or nFrames. Not crucial though, if the code
doesn't crash.
Michael

**Comment by swift505** [comment]
Thank you both very much. Those changes seem to fixed both issues.
