### ISSUE TITLE
error in get_svdForROI

### ISSUE THREAD

**Issue by swift505** [cortex-lab/Suite2P#39]
Hi Marius,

I'm getting the following error:

***
Subscript indices must either be real
positive integers or logicals.

Error in get_svdForROI (line 47)
    mov(:,:,ix + (1:size(davg,3))) =
    davg(ops.yrange, ops.xrange, :);
***

Checking ops.xrange and ops.yrange, I find they extend from 0 to 767 (for a 768x768 movie) but 0 is not valid for indexing davg.

Isaac

**Comment by marius10p** [comment]
Hi Isaac, did you get this error with rigid or non-rigid registration? Can you please tell me what 4 numbers you got in the command line just after registration (those are the maximum and minimum movements in X and Y).  Best, -Marius

**Comment by swift505** [comment]
Hi @marius10p 
  This was with rigid registration.
  My movie is 768x768 pixels x 881 frames.
  The bidirectional offset was 0 and 4 numbers were  -0.2, 0, 0, 0.1.
  I've just run it again after the updates to the registration code and the error persists.
Thanks, -Isaac

**Comment by marius10p** [comment]
Ok, I see the problem and I just fixed it. You have so little movement!

Please re-open if there are still issues.

**Comment by swift505** [comment]
Hi Marius,

There's a small error you'll want to correct:

***
Error: File: reg2P.m Line: 226 Column: 44
Unbalanced or unexpected parenthesis or
bracket.

***

**Comment by swift505** [comment]
@marius10p 
Other than the minor error you should correct (see above), get_svdForROI now works for me.
Thanks, -Isaac

**Comment by marius10p** [comment]
got it, thanks!
