### ISSUE TITLE
Integrating red and green channels

### ISSUE THREAD

**Issue by MarioDipoppa** [cortex-lab/Suite2P#4]
It is important to integrate information from the red channel with that from the green channels. The ROIs detection should be independent in the two channels, and the second one only needs the mean fluorescence (this detection could be an option of the gui). Once the ROIs of somata and dendrites are selected, one could compare the two (this could be another option of the gui). Looking at the contour the gui/and or the user will decide whether to merge two overlapping ROIs or delete the overlap.

**Comment by marius10p** [comment]
Suite2p now detects cells in the red channel, and the GUI displays these in red. The user can override classification with middle-mouse-click. We should discard cells detected in the red channel which have not been previously detected as having activity in the green channel. This is to avoid ROIs with no signal but just neuropil contamination.
