### ISSUE TITLE
gui2P background and mask

### ISSUE THREAD

**Issue by ZeitgeberH** [cortex-lab/Suite2P#42]
For better visual inspection, the background should remain visible when changing the mask.
For example,  when choosing the mean projection as background, the mask should be overlaid 
on the mean projection.

**Comment by marius10p** [comment]
We have tried various ways of achieving an overlay, but it's very hard due to non-homogeneities in both images. Unless you have a specific proposal for how to do the overlay, I suggest you keep flipping between the different views to get a sense of whether something is an ROI or not. That is what the keyboard shortcuts are for.

**Comment by ZeitgeberH** [comment]
Hi Marius,

thanks for the explanation.  Can you say a little bit more about the non-homogeneities issue? 

For my application, something like this would be helpful.
![test1](https://cloud.githubusercontent.com/assets/7234420/22348030/2762fff4-e3d8-11e6-98f1-c6ed6cf51ec1.png)

By modifying code in the "redraw_figure.m" 

axes(h.axes2); 
imagesc(h.dat.mimg(:,:,2));colormap('gray');
hold on;
hclust1=imagesc(I);
alpha_clust1=ones(h.dat.cl.Ly, h.dat.cl.Lx);
alpha_clust1(iclust1>0)=0.3;
alpha_clust1(iclust1==0)=0.2;
set(hclust1,'AlphaData',alpha_clust1);
axis off;

Best,
Ming

**Comment by marius10p** [comment]
Hi Ming,

Your image is also non-homogeneous: there are dark and light areas. In general, when an ROI 
is very clear on the mean image, one can determine that easily from any of the views. When an ROI is less clear, then the overlay makes it even harder to resolve features visually. Hence why I prefer to keep both views separate, for better viewability. 

Best,
   Marius
