### ISSUE TITLE
Bug when selecting db(i).planesToProcess

### ISSUE THREAD

**Issue by MarioDipoppa** [cortex-lab/Suite2P#5]
When this option is used the following error appears

Warning: File not found or permission denied 

> In run_pipeline (line 38)
>   In master_file (line 66)

**Comment by marius10p** [comment]
I have removed this option completely for now. planesToProcess is incompatible with too many things right now, and it will require a much more careful integration. 

The pipeline now always processes all planes simultaneously.

**Comment by marius10p** [comment]
Suite2p is so fast that we shouldn't really need to process less than all planes at any times. I am closing this issue.
