### ISSUE TITLE
Suite 2P not converging.

### ISSUE THREAD

**Issue by rswilliamson** [cortex-lab/Suite2P#51]
I have a few recordings where Suite2P doesn't converge and continues to identify ROI's. Is it possible to change the stopping criterion in the master_file?

Example terminal output:
3957 total ROIs, err 1.1211, thresh 0.0022 
3969 total ROIs, err 1.1205, thresh 0.0022 
3980 total ROIs, err 1.1201, thresh 0.0022 
3993 total ROIs, err 1.1199, thresh 0.0022 
4003 total ROIs, err 1.1193, thresh 0.0022 
4014 total ROIs, err 1.1192, thresh 0.0022 
4023 total ROIs, err 1.1187, thresh 0.0022 
4033 total ROIs, err 1.1191, thresh 0.0022 
4046 total ROIs, err 1.1182, thresh 0.0022 
4056 total ROIs, err 1.1178, thresh 0.0022 
4068 total ROIs, err 1.1174, thresh 0.0022 
4080 total ROIs, err 1.1175, thresh 0.0022 
4095 total ROIs, err 1.1169, thresh 0.0022 
4110 total ROIs, err 1.1165, thresh 0.0022 
4118 total ROIs, err 1.1163, thresh 0.0022 
4129 total ROIs, err 1.1158, thresh 0.0022 
...

**Comment by marius10p** [comment]
For now, use ops.stopSourcery to stop it earlier. The default value is 1/20. Sourcery stops on the first iteration which finds less than this fraction of the number of ROIs found on the first iteration. 

I will come back with a more robust solution later.

**Comment by geffenlab** [comment]
I think I am getting a similar error - is it related (see below) there is also a warning. I tried adding in ops.stopSourcery but it did not do anything - what kind of value would be good to set it to?
Matlab output:
65 total ROIs, err 1.5692, thresh 0.0048 
118 total ROIs, err 1.5419, thresh 0.0048 
166 total ROIs, err 1.5232, thresh 0.0048 
217 total ROIs, err 1.5087, thresh 0.0048 
268 total ROIs, err 1.4962, thresh 0.0048 
314 total ROIs, err 1.4855, thresh 0.0048 
364 total ROIs, err 1.4755, thresh 0.0048 
411 total ROIs, err 1.4677, thresh 0.0048 
461 total ROIs, err 1.4605, thresh 0.0048 
503 total ROIs, err 1.4555, thresh 0.0048 
551 total ROIs, err 1.4493, thresh 0.0048 
594 total ROIs, err 1.4449, thresh 0.0048 
635 total ROIs, err 1.4406, thresh 0.0048 
672 total ROIs, err 1.4373, thresh 0.0048 
698 total ROIs, err 1.4350, thresh 0.0048 
719 total ROIs, err 1.4335, thresh 0.0048 
> In sourcery (line 137)
  In run_pipeline (line 76)
  In master_file(line 67) 
Warning: Matrix is close to singular or badly scaled. Results may be inaccurate. RCOND =  3.007762e-10. 
734 total ROIs, err 1.4325, thresh 0.0048

**Comment by rswilliamson** [comment]
What's your SNR like? I've found that this error is normally associated with my lower SNR recordings (more prevalent in deep recordings). A stopSourcery of around 1/10 is usually good enough to alleviate issues.

**Comment by marius10p** [comment]
@geffenlab I see that you fixed it by increasing the threshold. It might have been an issue with the conditioning of the matrix inversion in line 137 of sourcery, which I had turned off (what the warning refers to). I turned that back on, so you could try it again.

**Comment by geffenlab** [comment]
I tried 1/10 and I got the same warning (if you leave it going it does not find any ROIs, or just a few weird looking ones). What actually worked was to set the stopSourcery as 1/40...
Marius, I will try with the fix you have implemented on Monday - thanks!

**Comment by marius10p** [comment]
A recent update fixes this problem. Closing this issue. Please reopen if there are still problems?

**Comment by Kelarion** [comment]
Hi Marius, I've recently run into this problem myself on some older data (using Suite2P downloaded today, and on the 15th). Setting stopSourcery to 1/10 fixed it, but I thought it would be good to mention in case the issue pops up for other people. 

-Matteo A
