### ISSUE TITLE
Abnormal periodic signal in fluorescence traces and running deconvolution

### ISSUE THREAD

**Issue by ALourdiane** [cortex-lab/Suite2P#61]
Hi,

I'm having a problem when running the scripts, probably will you be able to help.
Basically, my problem concerns the fluorescence and neuropil traces in the result folder, in which a periodic signal (alike a second trace) is present. This can be seen below: 

![image](https://cloud.githubusercontent.com/assets/28299274/25667737/b629838c-3024-11e7-82e4-bca91a566549.png)

Would you have any idea of what could this be due to? When I image it in the GUI it is not visible due to the smoothing steps, but this has automatically a huge impact on the traces I see.

Also, the computers I have tested suite2P on were blocked at the parallel processing step after the initiation of the deconvolution (ran for 24 hours before I stopped). I stop at this running step:

![image](https://cloud.githubusercontent.com/assets/28299274/25667843/0f9d66ea-3025-11e7-9a8a-3dd3350231e9.png)

When I terminate the operation on purpose, the program is always at the same location (I precise that I compiled the C file):

![image](https://cloud.githubusercontent.com/assets/28299274/25667898/3ca0de9c-3025-11e7-932a-090c09ab21eb.png)

Again, would you have any advice to give for me to run this program smoothly?

Thanks a lot in advance for your help !

Anthony

**Comment by marius10p** [comment]
Hi, 

Did you close this issue on purpose or by accident? 

Give me a few days to fix the spike deconvolution, I think my last update broke it. 

As for the traces, could there be something wrong with the order of the frames? It seems that Suite2p has picked them up in the wrong order. Is this a multi-plane or a multi-channel recording?

**Comment by ALourdiane** [comment]
Hi,

I closed the issue after using my own analysis of the traces on the ROIs detected by your algorithm, but this is still a problem when using S2P, thanks for your comment. I reopen it. 
These traces are from a 1-plane single-channel recording, and the order of the traces seems to be good when I draw the fluo outside S2P

Anthony

**Comment by marius10p** [comment]
what is the period of the artifact? does it correspond to any number relevant in your experiment, like the number of frames per tiff or something like that?

**Comment by ALourdiane** [comment]
The period for the artifact is 11 frames, but it does not correspond to any relevant feature of our experiment so far.
So I checked the fluo traces of the exact same ROI with S2P, with my own extraction of the very same pixels given by S2P, and with a circle approximation in imageJ. The ROI detection is good but the traces seem to have a confusing factor in their computation. You can see the results below:

with S2P:
![image](https://cloud.githubusercontent.com/assets/28299274/25782676/a4e6fbbc-334f-11e7-80ef-9aca0f8d0ffc.png)


with my extraction: 
![image](https://cloud.githubusercontent.com/assets/28299274/25782685/e601dc0c-334f-11e7-9353-1e2c7e782903.png)


with imageJ:
![image](https://cloud.githubusercontent.com/assets/28299274/25782687/ecf917e6-334f-11e7-955d-ab4684925a80.png)

**Comment by marius10p** [comment]
I fixed the spike deconvolution now, it should no longer hang. 

Please let me know if you figured out the problem with the periodic frame. I haven't really seen that before with tiffs coming from other microscope systems, hence why I think it has to do with your particular tiff somehow (how many frames per tiff do you have? what resolution? could you upload one of your tiffs somewhere?).
