### ISSUE TITLE
separating spike times/amps when you have processed 2+ recordings together

### ISSUE THREAD

**Issue by geffenlab** [cortex-lab/Suite2P#62]
Hi
I have processed two recordings together through suite2P and the calcium traces are easily separated into the two blocks (i.e. FCell has two cells, one for each block). Is there a way you could implement this for the spike times and amplitudes?  
As it is now, do the spike times correspond to the two blocks concatenated? (e.g. if I have two blocks of 100 images, spike times of 5 and 105 would correspond to frame 5 of the two blocks?)
Thanks,
Kath

**Comment by marius10p** [comment]
Hi Kath, I have added that recently, but don't update yet because I think the old spike deconvolution is now broken. Sometime mid next week I will make a change that will fix and update the deconvolution method; we have some new results there. Cheers, -Marius

**Comment by marius10p** [comment]
Spike deconvolution is fixed, and the output is in a cell for each block of the experiment. Let me know if there are any more problems.
