### ISSUE TITLE
File size

### ISSUE THREAD

**Issue by christinabuetfering** [cortex-lab/Suite2P#64]
Hi Marius and Carsen,

I have a quick question about processing large files. 
Do I understand it correctly, that I should expect a suite2p error  if the binary file is larger than the RAM of my computer? (At least that's what I am experiencing and I assume that it is because it needs to load in the binary file into the RAM at some point. Is that right?).
If not - do you have any idea why this is happening?
If yes - is there anything other than increasing the RAM that you could think of that would allow me to process files larger than the RAM of my computer? 

Cheers,
Christina

**Comment by marius10p** [comment]
Hi Christina. The binary file is never loaded all at once into RAM. Can you please tell us at what step of the analysis you run out of memory? Cheers, - Marius

**Comment by christinabuetfering** [comment]
Hi Marius,

That's good news I guess (-:

This is the error that I get is this: 

master_file_cb_6s
Running on sessioncb100/20170429/1  2  3  4  5  6  7  8
running rigid registration
bi-directional scanning offset = 0 pixels
Set 1, tiff 1 done in time 609.64 
Set 2, tiff 1 done in time 1017.71 
Set 3, tiff 1 done in time 1427.79 
Set 4, tiff 1 done in time 1840.82 
Set 5, tiff 1 done in time 2259.63 
Set 6, tiff 1 done in time 2689.49 
Set 7, tiff 1 done in time 3104.49 
Set 8, tiff 1 done in time 3506.04 
   -7.6000    6.2000   -3.8000    2.9000

85 total ROIs, err 1.1917, thresh 0.0891 
162 total ROIs, err 1.1055, thresh 0.0891 
233 total ROIs, err 1.0502, thresh 0.0891 
291 total ROIs, err 1.0118, thresh 0.0891 
354 total ROIs, err 0.9821, thresh 0.0891 
415 total ROIs, err 0.9565, thresh 0.0891 
470 total ROIs, err 0.9312, thresh 0.0891 
522 total ROIs, err 0.9128, thresh 0.0891 
573 total ROIs, err 0.8927, thresh 0.0891 
625 total ROIs, err 0.8755, thresh 0.0891 
678 total ROIs, err 0.8615, thresh 0.0891 
721 total ROIs, err 0.8497, thresh 0.0891 
758 total ROIs, err 0.8387, thresh 0.0891 
791 total ROIs, err 0.8285, thresh 0.0891 
816 total ROIs, err 0.8210, thresh 0.0891 
840 total ROIs, err 0.8156, thresh 0.0891 
859 total ROIs, err 0.8105, thresh 0.0891 
875 total ROIs, err 0.8057, thresh 0.0891 
890 total ROIs, err 0.8017, thresh 0.0891 
902 total ROIs, err 0.7980, thresh 0.0891 
909 total ROIs, err 0.7973, thresh 0.0891 
919 total ROIs, err 0.7950, thresh 0.0891 
919 total ROIs, err 0.7950, thresh 0.0891 
Frame 6000 done in time 50.40 
Frame 12000 done in time 107.71 
Frame 18000 done in time 169.85 
Frame 24000 done in time 230.39 
Frame 30000 done in time 291.73 
Frame 36000 done in time 355.58 
Frame 42000 done in time 419.05 
Frame 48000 done in time 481.03 
Frame 54000 done in time 541.39 
Frame 60000 done in time 598.91 
Frame 66000 done in time 655.04 
Frame 72000 done in time 710.91 
Frame 78000 done in time 767.06 
Frame 84000 done in time 823.00 
Frame 90000 done in time 878.66 
Frame 96000 done in time 933.70 
Frame 102000 done in time 988.65 
Frame 108000 done in time 1045.84 
Frame 114000 done in time 1103.66 
Frame 120000 done in time 1161.01 
Frame 126000 done in time 1220.30 
Frame 132000 done in time 1281.92 
Frame 138000 done in time 1345.00 
Frame 144000 done in time 1410.00 
Frame 150000 done in time 1474.41 
Frame 156000 done in time 1539.63 
Subscript indices must either be real positive integers or logicals.

Error in my_ica (line 17)
    ca(:,i0)   = filtfilt(b1, a1, ca(:,i0));

Error in extractSignalsNoOverlaps (line 146)
[coefNeu, inomax]   = my_ica(F', Fneu', ops.fs, 0.7, ops.maxNeurop);

Error in run_pipeline (line 89)
                [ops, stat, Fcell, FcellNeu] = extractSignalsNoOverlaps(ops, model, stat);

Error in master_file_cb_6s (line 80)
    run_pipeline(db(iexp), ops0);

**Comment by marius10p** [comment]
Hmm, runs out of memory during neuropil estimation. No problem, we removed that step recently (it is now estimated together with spike deconvolution). 

Can you please update the repository and try again?

**Comment by christinabuetfering** [comment]
Sure! Will do and let you know. Thanks Marius!

**Comment by christinabuetfering** [comment]
Hey - it ran fine for 6 subsessions (~60GB) but I only realised now that deconvolution and neuropil estimation was still commented out. I will put it back and run it again later tonight.

**Comment by marius10p** [comment]
You don't need to re-run the whole thing, just the deconvolution part. It will load the respective files from disk.

**Comment by christinabuetfering** [comment]
It ran through beautifully with 8 subsessions (~80GB) and deconvolution! Nice ((-: Thanks Marius!
