### ISSUE TITLE
Add skewness and (other fields) to F...proc.mat file

### ISSUE THREAD

**Issue by hwpdalgleish** [cortex-lab/Suite2P#66]
Hey,

Please add fields to the F...proc.mat file containing images of skewness and any other useful masks so that they can be displayed in RegisterS2P.

Thanks,
Henry

**Comment by carsen-stringer** [comment]
Hey Henry, do you want them in RGB format? I've added them to the proc file now as RGB maps (saved in dat.cl.skewFig, dat.cl.cmpctFig, ....). sorry for the delay on this!

**Comment by hwpdalgleish** [comment]
Hey Carsen, no worries - I'm sure you and Marius have been busy with the move! I was thinking they could be in a similar format to the dat.mimg and dat.mimg_proc fields. I think these are just double. Is there any reason these other fields need to be RGB?

**Comment by carsen-stringer** [comment]
I think it's easier to see it as RGB - that's what we're using in the GUI currently. If you just have a single linear colormap, then cells that have low skewness will just be black (you won't see their shape). Would you prefer something like this instead?

**Comment by hwpdalgleish** [comment]
Keep it as RGB for now, I can always convert it to a double if necessary. As you say - it would suck to lose information, although maybe for the registration it's not completely essential.

**Comment by carsen-stringer** [comment]
If you want these for more than display purposes I'd recommend using the numerical values from dat.stat. I do some logarithmic scaling with these so the differences are noticeable by eye.
