### ISSUE TITLE
Spike deconvolution

### ISSUE THREAD

**Issue by horsto** [cortex-lab/Suite2P#67]
Hi Marius, 
is the spike deconvolution fixed? When I try to use it I get warnings (see below) and "st" does not appear under stats anymore in the output.  I know it's still commented out in the master_file_example.m, but I thought I'd give it a go...

```
In wrapperDECONV (line 45)
In add_deconvolution (line 51)
In run_pipeline_masterfile (line 39) 
Warning: Matrix is close to singular or badly scaled. Results may be inaccurate. RCOND =  1.133285e-07.
```

**Comment by marius10p** [comment]
Yes, it's supposed to be fixed, but now it's in "sp". This is a cell containing the deconvolved spikes for each block separately (so just like Fcell and FcellNeu). I'm not sure what your warning is about, but could be a trace that's all zeros or NaNs.

**Comment by horsto** [comment]
Thanks for the reply!
I have a follow-up question. Spike deconvolution (in its preconfigured state) now seems to extract a lot of noise (see below, _sp_ filtered >10 and >30 (>0 shows basically a continuous line of red dots)). This didn't happen when I ran the previous version of Suite2P (about 2 months ago?).  
Is this normal? Is there a way to rationalize a threshold for extracted spikes? (I am more interested in the spike times than the actual number of extracted spikes)
I played around with _sensorTau_ and _maxNeurop_, which doesn't seem to have drastic effects (unless for example sensorTau is set to values >20, ...). I also tried to compare to OASIS, which I assumed would run as an alternative to L0, but it throws the error I attached below. 
Thanks!

**>10**
![tau_decay 8_filter_10](https://cloud.githubusercontent.com/assets/7548928/26355784/412d2628-3fca-11e7-9974-8237e541c253.png)
**>30**
![tau_decay 8_filter_30](https://cloud.githubusercontent.com/assets/7548928/26355806/4ea9d2ec-3fca-11e7-9e98-015329d50d4e.png)

```
Error using OASISpreprocess (line 111)
An UndefinedFunction error was thrown on the workers for 'oasisAR1'.  This might be because the
file containing 'oasisAR1' is not accessible on the workers.  Use addAttachedFiles(pool, files)
to specify the required files to be attached.  See the documentation for
'parallel.Pool/addAttachedFiles' for more details.
```

**Comment by marius10p** [comment]
Hmm, not sure what change would have resulted in the difference. Those results look reasonable to me, unless you have a reason to believe the single spike response is larger than the events the algorithm identified. There is a penalty parameter that you can use to sparsify the results. The default is ops0.lam = 3 (I think it has always been that), and you can increase to sparsify. OASIS will give you even less sparse outputs, since it's using an L1 penalty rather than L0. 

Btw, there will be an update to the Suite2p paper soon that looks at this kind of issue in more detail.

**Comment by horsto** [comment]
Great, thanks, I will play with the lam parameter as well. Any idea why my attempt to run OASIS isn't going well (see error I pasted above)? Is that a problem on my side only? 

I am looking forward to the updated Suite2p paper.
Are you planning any major adjustments to the (deconvolution) code in the near future?

**Comment by marius10p** [comment]
You need to have this repository in your path https://github.com/zhoupc/OASIS_matlab

There won't be any changes to the algorithm, that has actually not changed in a while. There will be changes to the default parameters which we recommend, which will actually go in the direction of a more dense output (lower ops0.lam).  There is reason to believe too much sparsification misses spikes.
