### ISSUE TITLE
jumping frames after registration

### ISSUE THREAD

**Issue by christinabuetfering** [cortex-lab/Suite2P#73]
Hi Marius, Carsen and co.

I am having problems with registration related to the closed issue "Phase correlation alignment glitch?" (I also tried to reopen and found out that that's not an option (-;). 
I am getting mis-aligned frames after registration (my data: sparse activity in L3 barrel cortex with 6f transgenic - so SNR is on the low side). There are two rather bright cells and the main issue seems to be that is is mapping the one cell onto the other including a shift by around 40 pixels. 

I tried the db(i).smooth_time_space option but it crashes my matlab (on both of my computers on of which has 64GB RAM and an 8GB Nvidia graphics card so I would think it is not too easy to crash...). .
I smoothed the .tiff files externally with a gaussian filter (spatial smoothing, std = 1) but it didn't help but I also didn't explore temporal smoothing or stronger spatial smoothing.
I played with the registration options (ops0.dobidi; rigid and non-rigid; non-whitened phase correlation; played with ops0.SubPixel, NimgFirstRegistration and mingbegend) but none of them seem to affect the outcome which is a few misaligned frames in the registered tif.

So I was wondering:
Is the db(i).smooth_time_space option still supported? Or do you know why it might make matlab crash?
Do you have any recommendation regarding things for me to try?

Any feedback would be super great! (-:
Thanks!

**Comment by marius10p** [comment]
Strange that you couldn't re-open the other issue, I just did (and I closed it back again). Let's continue the discussion here.

**Comment by marius10p** [comment]
The smoothing should work. Sometimes, old versions of Matlab crash with the newest Nvidia GPUs (10xx), so it would be worth installing 2017a, as it's the only version that "officially" supports GTX 10xx. Otherwise, maybe your tiffs are very large? Though I think we split each tiff in batches.

Btw, if there are just a few misaligned frames, we now have an automatic step that detects those and excludes them. You will see NaNs for those timepoints in the final traces. You could also look by eye at those frames to check there is nothing there to align to.

**Comment by christinabuetfering** [comment]
Yep - only collaborators can (-:. 

I am running Matlab 2017a and updated suite2p yesterday. I am using a Quadro M4000 - do you know if you would expect problems with that one?  My tiffs are 20.000 frames (10GB) but as you said, the registered tiffs are being split in chunks of 2000 frames. I can run it again later and see where it gets stuck. 
Have you seen that the temporal or spatial smoothing actually helped? From the old issue it sounded like it was not particularly effective in preventing the glitches. 

What I find difficult to understand is that there are two clearly bright cells that I would think would make it very easy to align those frames. The alignment is not off because it is dark but because it is wrongly assigning one cell on top of another cell. Would it be difficult to add a maximum_shift_allowed in pixels to suppress big jumps? 

Automatic detection sounds interesting - either to check if there is misalignment or to delete if nothing else works. Is the detection of misaligned frames already implemented or some code to run after the registration?

**Comment by marius10p** [comment]
The detection of  misaligned frames is already implemented, Also, spatial and temporal smoothing can definitely help at the low SNR range. 

I have no idea what the Quadro card would do, but assuming its drivers are up-to-date, it should work fine. 

Maybe there is still a place in the code where the tiffs are not split into batches. If so, let me know where the error is. We usually work with much smaller tiffs (up to 2000 frames/tiff).

If the maximum correlation is obtained by aligning the wrong cells, that's just what it is, unless there is a bug somewhere (check the mean image maybe?). Have you checked if those frames specifically are unusual? Maybe a third cell lit up or something? There is already a limit on how large of a jump it allows. This option is ops.maxregshift, by default a tenth of your maximum XY length. You can change this.

**Comment by christinabuetfering** [comment]
That's interesting that you are already removing misaligned frames. The reason i noticed the misalignment of frames is because my FOV was cropped by around 100 pixels. (movie was 512x512) and only ROIS within the smaller FOV were detected. When I looked into it I found the misaligned frames and reasoned that that would cause the cropping. Could you potentially detect the misaligned frames earlier in the pipeline so that they are not taken into account for the segmentation/signal extraction? 

I tracked down the crash when using the smooth_time_space option and it happens in my_conv(S1,sig) (called by my_conv2 - called by smooth_movie - called by GetRegOffset - called by reg2P). It is attempting to apply the gaussian filter on the full movie 
	S1 = filter(gaus,1,cat(1,S1,zeros([tmax,dsnew2(2)]))); 
with S1 being the unsplit movie. 
Will you have time to add splitting for the smooth option? (Otherwise I will give it a go (-;). 

The frames in the raw movie look normal - no sudden movement artefact - but I can see how aligning the wrong cells might give a good correlation if the two signals are changing quickly. 

I will also try changing maxregshift to a smaller value - took me a moment to find the option in the depth of suite2P (-;

Ok cool, so lots of options with smoothing and maxregshift to try to tackle these jumps! Many thanks for the help and the super quick reply Marius!

**Comment by christinabuetfering** [comment]
PS. Changing maxregshift to 5% fixed the jumping frames-issue in my test video (-:
