### ISSUE TITLE
code overwrites new parameters with old parameters

### ISSUE THREAD

**Issue by MichaelGMoore** [cortex-lab/Suite2P#74]
If I run suite2p on a dataset, and then decide to run it again using different parameters, the code will ignore my new parameters and run it using the old parameters, but without indicating that it does so. The reason is that the code handles the ops and ops0 and ops1 parameters in a kind of complicated dance, and the old parameters are stored in the regops file. The code looks for this file and if it exists, then it overwrites the new parameters with the old. The work-around is to delete the regops file when you change the parameters. This was pretty confusing and I ran lots of data before I realized this was happening.

**Comment by carsen-stringer** [comment]
I've fixed this now, please let me know if you still have issues with this
