### ISSUE TITLE
Offset issue with ROIs in sorting GUI

### ISSUE THREAD

**Issue by MichaelGMoore** [cortex-lab/Suite2P#75]
When I run the ROI sorting GUI, I have an issue where the ROI that I click on is not the one that is moved from one category to the other. Instead it moves one that is shifted by several pixels. I am running  Matlab2017a on a Red Hat Enterprise Linux Box. I imagine this could be a glitch between Matlab and the operating system. Have you seen any reports of this issue? It makes the GUI pretty much unusable on my machine.

**Comment by carsen-stringer** [comment]
Is this still an problem? I'm running the Suite2P GUI on ubuntu 16.04 (matlab 2017b) without this issue

**Comment by MichaelGMoore** [comment]
I am running matlab 2017b on Redhat Enterprise Linux Server Edition. I just
ran some tests, and I didn't notice the problem. If I run into it again, I
can let you know.

Cheers,
Michael
