### ISSUE TITLE
registers2p won't run

### ISSUE THREAD

**Issue by hwpdalgleish** [cortex-lab/Suite2P#77]
A user reported the following error when running registers2p:

">> registers2p
Error using image
Incorrect number of arguments.

Error in imagesc (line 39)
    hh = image(varargin{:},'CDataMapping','scaled');

Error in registers2p>registers2p_OpeningFcn (line 125)
handles.image_display = imagesc(handles.image_axis,handles.files(1).image{1}(:,:,1),'ButtonDownFcn',@lasso_targets);

Error in gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

Error in registers2p (line 42)
    gui_mainfcn(gui_State, varargin{:});"

This appears to be because the inbuilt MATLAB "image" function only added the ability to take an axis handle as first argument after MATLAB 2015b. If you see this error please try updating to at least 2016a and re-running.

Cheers,
Henry

**Comment by carsen-stringer** [comment]
Hey Henry, do you want to add this to the readme in registers2p instead of having it here?

**Comment by hwpdalgleish** [comment]
Done!

**Comment by carsen-stringer** [comment]
thanks :)
