### ISSUE TITLE
ichanset(1) off by 1?

### ISSUE THREAD

**Issue by llerussell** [cortex-lab/Suite2P#8]
in reg2Pnew.m, line 60

ichanset(1), the index of the first Tiff page to load, seems to consistently be off by 1. It is always 2 in my hands. This prevents being able to process a folder of single-page tiffs, but is generally OK with multipage tiffs.

**Comment by marius10p** [comment]
Hi Lloyd, I see the problem. We generally start from the second image because the very first image is random. We only really need to do this on the first tiff in the series. I will think about how to make it compatible with single-page tiffs.

**Comment by marius10p** [comment]
I fixed this now. It was only a problem for computing the target image. Should work now, but I don't have single page tiff data to test it.

**Comment by marius10p** [comment]
I will close this issue, but leave issue #23 outstanding, until I verify that it can work correctly on a folder of single-page tiffs.
