### ISSUE TITLE
How to specify that there is no red channel

### ISSUE THREAD

**Issue by bill-connelly** [cortex-lab/Suite2P#83]
Looking at some of the variables (like firstIdx) I think Suite2p is thinking I have two channels.

What variables do I set in make_db or master_file to let suite2p know that there is only one channel?

Or is that impossible? If so, how do I get it to ignore the red channel? I've already got db(i).AlignToRedChannel= 0

**Comment by marius10p** [comment]
If you do not set any red channel options anywhere, it will assume one channel.  You can enforce this option by setting db(i).nchannels = 1. But this should really be the default, unless your tiff headers contain the information as a tag.
