### ISSUE TITLE
Re-registering files when working on the same file

### ISSUE THREAD

**Issue by bill-connelly** [cortex-lab/Suite2P#86]
I'm trying to analyse the same file using different settings in make_db.m however registration is being performed every time. Though other times, the "already registered binary found" comes up, and no re-registration is performed. I can't figure out why it happens sometimes and not others.

master_file.db contains:

ops0.RootStorage            = 'G:/test/'; % Suite2P assumes a folder structure, check out README file
ops0.temp_tiff              = 'G:/temp/temp.tif'; % copies each remote tiff locally first, into this file
ops0.RegFileRoot            = 'G:/temp/';  % location for binary file
ops0.DeleteBin              = 1; % set to 1 for batch processing on a limited hard drive
ops0.ResultsSavePath        = 'G:/temp/F'; % a folder structure is created inside
ops0.RegFileTiffLocation    = 'G:/temp/'; % leave empty to NOT save registered tiffs (slow)

Commands and output

>clear all
>master_file

**running rigid registration**
bi-directional scanning offset = 0 pixels
Set 1, tiff 1 done in time 140.90 
  -47.1000   49.3000  -51.6000   45.3000

202 total ROIs, err 0.5249, thresh 0.0042 
383 total ROIs, err 0.5218, thresh 0.0042 
483 total ROIs, err 0.5200, thresh 0.0042 
528 total ROIs, err 0.5192, thresh 0.0042 
537 total ROIs, err 0.5190, thresh 0.0042 
537 total ROIs, err 24693.7070, thresh 0.0042 
537 total ROIs, err 24625.1270, thresh 0.0042 
537 total ROIs, err 24619.3594, thresh 0.0042 
Frame 6000 done in time 8.32 
Spike deconvolution, plane 1... 
> clear all
> master_file

**running rigid registration**
bi-directional scanning offset = 0 pixels
Set 1, tiff 1 done in time 135.37 
  -47.1000   49.3000  -51.6000   45.3000
...

**Comment by marius10p** [comment]
It is able to skip registration if it finds two files: 1) the regops file, containing the settings of the previous run; 2) the binary registered files. These have to be placed at the correct location based on current settings. So if you change output file paths in-between runs, it won't be able to find the previous run. Could this explain your issue?

**Comment by bill-connelly** [comment]
I think it is coming from ResultsSavePath in the  regops structure. On both mine, and a colleagues computer this is being created as 'G:/temp/F//32645//2017-07-27//1//'  I think that is due to

 ops.ResultsSavePath = sprintf('%s//%s//%s//%s//', ops.ResultsSavePath, ops.mouse_name, ops.date, ...
    CharSubDirs);

in build_ops3.

Exactly why it works sometimes and not others is a bit beyond me though, maybe I was changing things

**Comment by carsen-stringer** [comment]
You're running suite2p with ops0.DeleteBin=0. Your binary files will therefore have been removed after running cell detection -- maybe sometimes you ran cell detection and other times didn't. Also try to run "fclose all" to make sure you aren't still reading or writing into the files. please re-open this if you're still having issues
