### ISSUE TITLE
Making fixed variables as input parameters

### ISSUE THREAD

**Issue by MarioDipoppa** [cortex-lab/Suite2P#9]
in get_signals_and_neuropil, neuropil radius, microscope zoom, inner radius of the neuropil mask are fixed variables. We should make them input parameters in make_db. Number of pixels of each frames can instead be read from the tiff file.

**Comment by mkrumin** [comment]
Microscope zoom is extractable from the tiff header:
e.g. scanimage.SI4.scanZoomFactor = 2 for zoom 2. However, the field of view is not a linear function of the zoom, and also it is slightly different in x and y.

**Comment by xigumalu** [comment]
Also, the relationship between zoom factor and field of view is different for our two microscopes. Ideally, there would be a look-up table relation zoom to field of view size for each microscope.

**Comment by MarioDipoppa** [comment]
The software take already in account these two features: it distinguishes between the different microscopes and assign a um to pixel conversion for few values of zoom values.

**Comment by marius10p** [comment]
I have added a user input called "diameter" for the average cell diameter. All the anatomical processing is now done relative to this number, including neuropil computation in the "model" case. The "surround" option could also use this variable, if Mario implements it.

**Comment by marius10p** [comment]
Since the "diameter" option is now crucial to the cell detection functions, things like zoom factor and field of view are redundant.

**Comment by xigumalu** [comment]
Does this mean that "get_signals_and_neuropil" does not use information about zoom factor and field of view anymore?
Also, what unit is the "diameter" option? If it is pixels it needs to be changed every time one uses a different zoom factor or a different number of pixels, which is a lot more inconvenient than deciding once for an appropriate neuron diameter in units of micrometers and then reading out zoom factor and number of pixels from the tiff-files (plus having a look-up table to convert zoom factor to field of view in units of micrometers for each microscope, which could be user supplied). Can this be changed?

**Comment by carsen-stringer** [comment]
can you set it as a function of the zoom that you input? We use db.diameter = db.zoom * 6 for instance

**Comment by xigumalu** [comment]
This means that one would need to set the zoom for each recording manually instead of reading it from the tiff header. Also not so convenient. In addition, the translation from pixels to magnification is not linear across zoom factors.
However, I don't think that the diameter setting is very crucial for ROI detection, is it?
For neuropil correction I use my own code now.

**Comment by carsen-stringer** [comment]
I've added this now to run_pipeline.m and build_ops3.m. If the zoom is not specified by the user and there is a zoom found in the tiff headers, then it's used to compute the diameter. The diameter is not used in the neuropil computation, only in sourcery.m for the width of the smoothing mask on the correlation map.

**Comment by carsen-stringer** [comment]
changing its value shouldn't have a big effect though, you're right

**Comment by xigumalu** [comment]
Ok, but how is zoom now used to compute the diameter? Are you using the infoPixUm function?

**Comment by carsen-stringer** [comment]
I just multiply the zoom by 8 as an approximate measure of diameter. You're welcome to use the infoPixUm function instead, it's just specific to our scopes so I didn't want to add it to run_pipeline.m (see line 15 for the computation)
