### ISSUE TITLE
Options for cell detection

### ISSUE THREAD

**Issue by xigumalu** [cortex-lab/Suite2P#90]
When re-running Suite2p on already registered data, all options/parameters (in ops) are set to the values that were chosen during the initial run (when regops...mat is loaded). However, it happens quite often that I'm happy with the registration but not with the ROI detection. It would be good if I could change parameters/options in master_file/make_db, and these new parameters were used for the new run of ROI detection (without registration again).
I think it happens to many people that they re-run ROI detection with new parameters but always get the same results back, because it is not obvious that the new parameter setting are simply overwritten.

**Comment by bill-connelly** [comment]
I have gotten this too. I delete everything to get the cell detection to work with new parameters. Probably not the smartest solution.

**Comment by carsen-stringer** [comment]
I've added a script to check for this in run_pipeline.m called opsChanges.m to fix this problem
