### ISSUE TITLE
specify number of planes and number of channels (when more than one)

### ISSUE THREAD

**Issue by MariangelaP** [cortex-lab/Suite2P#93]
Hi,
I have a tiff file containing an acquisition over two channels and two different planes. It looks like suite2p is assuming by default that the channel is only one. How can I specify that I have two? Where do I set info about number of planes?
If this is useful at all: my metadata contains NumberOfChannels=2; SI.hChannels.channelSave = 2.

many thanks

**Comment by marius10p** [comment]
We use the scanimage metadata, and default to 1 if not available. You can overwrite this with ops.nchannels = 2, ops.nplanes = 2. You can also set these parameters in db(k).nchannels = 2, db(k).nplanes = 2, in which case they overwrite ops, and can be set differently for different datasets k.   -Marius

**Comment by MariangelaP** [comment]
Hi Marius,
thanks for your quick reply. I've changed the parameters in make_db so to
set two channels and two planes for processing my 20000 frames acquisition.
However, although the registration seems to have been successful, the cell
detection has been going on now for over 15 hours now. Do you know why this
may be happening? Also, should the cell detection eventually produce two
different files, one for each plane, to open in new_main? I have a load
plane button on my version of the GUI (rather than a load single as
suggested in the documentation) so I guess acquisitions from different
planes should be separate?
I'm happy to provide more info about metadata and parameters set in the
master file, if needed.

Many thanks again for your time and help!

mariangela

2017-09-19 23:34 GMT+01:00 Marius Pachitariu <notifications@github.com>:

**Comment by marius10p** [comment]
Hi Mariangela,

If the cell detection is stuck, it's probable that something went wrong again during registration. 
You can try to set ops.maxIterRoiDetection = 5 or something like that, to see if cell detection finishes (the default is 100, but it should stop on its own after 5-10 iterations). Then you can inspect the output in the GUI and try to see what went wrong.  

Yes, there should be one file for each plane. 

Best,
   Marius

**Comment by MariangelaP** [comment]
Hi Marius,
I tried to change maxIterRoiDetection to 10. However, for some reason the
detection was reitereted 13 times for each plane, instead of 10, I think
(You can see this on the left of the screenshot attached). When looking at
the field on the GUI, the those weird clusters that look like lines come
up, although the cell detection on the left seems relatively good. Do you
know whether there is any other parameter I could change to make the
registration work better (and avoid the cell detection to get stuck)?

Also, I expected to be able to see also a stack of the red channels frames
in the guy, while the F_VIP41.1e_20170831_plane1.mat file that I obtained
only contains frames from one plane and the green channel.

many thanks,
mariangela


2017-09-21 11:00 GMT+01:00 Marius Pachitariu <notifications@github.com>:

**Comment by carsen-stringer** [comment]
Sorry for the delay on this, the mean red image (ops.mimgRED) wasn't being output from the script, I've fixed it now. you can also run
`identify_redcells_sourcery(db, ops);`
to add red cell labels to each cell that you can view in the GUI.

I can't see the attachment that you're referring to, can you upload it on the issue on github?

**Comment by carsen-stringer** [comment]
Are you still having issues with this? Please reopen this issue if you are, thanks.
