### ISSUE TITLE
Priors

### ISSUE THREAD

**Issue by scottcanoe** [cortex-lab/Suite2P#94]
It has been mentioned that one can change the prior to aim for finding a certain number of ROIs other than the default (which I think is 300 or 500). Can someone elaborate on how this is done? Which field(s) require modification in a prior.m config file?

Much thanks.

**Comment by marius10p** [comment]
There is no default number of ROIs: the algorithm adapts to the data. 

But there is a threshold on the correlation map (shown during processing and in the GUI), and a multiplier on this threshold,  that you can change:  ops.ThScaling (by default 1). Look in the GUI at the corr map, and if you see that there are good peaks that have not been picked up, lower the multiplier incrementally (try 0.5 maybe?).  Change it either in ops0.ThScaling, or just for the dataset you want db(k).ThScaling (which overwrites the ops setting, which overwrites the default of 1).

**Comment by scottcanoe** [comment]
Hi Marius, thanks for the speedy reply, and thanks for making this software publicly available. The main issue that I'm trying to solve is that quite often a single soma is broken into multiple ROIs. (It looks pretty clear that this isn't happening due to overlapping signals from different cells.) Do you have any advice for how to handle this problem?

**Comment by marius10p** [comment]
Is the split happening spatially, or do you get multiple overlapping pieces from the same cell?

**Comment by carsen-stringer** [comment]
We have implemented a new cell detection algorithm in the python version of suite2p (https://github.com/MouseLand/suite2p, it will also be implemented in matlab in the next month). Now the masks can expand to an unlimited size, this may solve your problem. Please reopen this issue if you're still having issues, thanks
