### ISSUE TITLE
standalone spike detection

### ISSUE THREAD

**Issue by geffenlab** [cortex-lab/Suite2P#95]
Hi Marius,
A couple of questions about the stand alone spike deconvolution:
- what's the difference between deconvolution_standalone and deconvolution_standalone2 ?
- these two functions don't seem to use the new OASIS thing - is that correct? I want to reanalyse some old data with the new spike deconvolution....
Thanks!
Kath

**Comment by marius10p** [comment]
Sorry for the delay in responding. Those are no longer the top level functions for spike deconvolution. Instead, check out wrapperDECONV(ops, F, N).  You can specify oasis with ops.deconvType = 'OASIS', or you can use the L0 deconvolution with ops.deconvType = 'L0'.

**Comment by geffenlab** [comment]
thanks
