### ISSUE TITLE
Sharing one example stack

### ISSUE THREAD

**Issue by mingguichen** [cortex-lab/Suite2P#97]
Hi, thank you so much for this wonderful package. I tried many times with my images, but it's a little hard for me to find the correct parameters with my data. Could you please share one example data to get me started with the package? If you could also share one example parameter file for that example data, that's awesome! Thank you very much.

**Comment by marius10p** [comment]
Hi, sorry for the delay. I have put some example data here: https://drive.google.com/open?id=0B649boZqpYG1amlyX015SG12VU0. It also has the corresponding master_file and make_db file. Depending on where you save these on your computer, you will need to adjust the paths in the master_file, following the instructions in there.

**Comment by mingguichen** [comment]
Thank you so much, Marius! It works great with your sample data. I am trying to figure out why my data doesn't work now. Do you think the frame rate matters? My data is only at 2 Hz. Based on your experience, what are the most important factors affecting cell detection? Thanks again!

**Comment by marius10p** [comment]
This data is about 3Hz, so similar. Can you please load your data in the GUI and take a screenshot of the "corr" image in visualization, background, then share it here? That could give us a clue. Also post the "roi" image in the same category, and double check that the registration worked well by plotting ops.DS.

**Comment by mingguichen** [comment]
Thanks a lot for all the help, Marius. It works perfectly for my data now after cloned the new suite2p. Again, thank you very much for all your amazing effort and guidance! Enjoy your weekend!
